[project]
name = "jp-collect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastparquet>=2026.5.0",
    "ipykernel>=7.3.0",
    "pandas>=3.0.3",
    "psycopg2>=2.9.12",
    "pyarrow>=25.0.0",
    "requests>=2.34.2",
]
